### ISSUE TITLE
what the problem ?

### ISSUE THREAD

**Issue by ManoaNosea** [xinntao/SFTGAN#14]
```
λ python test_sftgan.py.
Testing SFTGAN ...
1 a_lfwall12a2_proc
Traceback (most recent call last):
  File "test_sftgan.py.", line 63, in <module>
    output = model((img_LR, seg)).data.float().cpu().squeeze()
  File "D:\Programs64\Python-3.6.5\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\SFTGAN-master\pytorch_test\architectures.py", line 210, in forward
    fea = self.conv0(x[0])
  File "D:\Programs64\Python-3.6.5\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 3-dimensional input of size [3, 256, 256] instead
```

**Comment by xinntao** [comment]
Did you use your own test images?
You need to ensure the input tensor has the shape [1， 3， H， W]. From the error log, your input tensor has the shape [3, H, W].

**Comment by nanogram** [comment]
afaik, this issue comes from not being able to handle alpha channels in pictures.
I have run into this same issue as well. Could there be a possible fix for images with alpha?

**Comment by xinntao** [comment]
@nanogram Maybe you can find a solution for images with alpha in [ESRGAN-issue](https://github.com/xinntao/ESRGAN/issues/18).
